Bus Station/SKBusService/src/SKBusService/Controllers/SKBusStopController.cs
/*
 *  SKBusStopController.cs
 *  Assignment 5
 *  Created By:
 *      Soochang Kim, 7227663
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SKBusService.Models;
using Microsoft.AspNetCore.Http;

namespace SKBusService.Controllers
{
    public class SKBusStopController : Controller
    {
        private readonly BusServiceContext _context;

        // SKBusStopController constructor
        public SKBusStopController(BusServiceContext context)
        {
            _context = context;    
        }


        /// <summary>
        /// Album index page will be displayed
        /// </summary>
        /// <param name="orderby">order condition</param>
        /// <param name="number">list number to display on one page</param>
        /// <param name="page">present page number</param>
        /// <returns></returns>
        public async Task<IActionResult> Index(string orderby = "", int number = 0, int page = 0)
        {
            var recordset = (orderby == "location") ?
                await _context.BusStop.OrderBy(a => a.Location).ToListAsync() :
                await _context.BusStop.OrderBy(a => a.BusStopNumber).ToListAsync();

            if (number == 0)
            {
                number = 10;
            }
            else
            {
                HttpContext.Session.SetInt32(nameof(number), number);
            }

            if(HttpContext.Session.GetInt32(nameof(number)) != null)
            {
                number = int.Parse(HttpContext.Session.GetInt32(nameof(number)).ToString());
            }

            int total = recordset.Count / number;
            ViewData["orderby"] = orderby;
            ViewData["page"] = page;
            ViewData["total"] = total;

            if(page == -1)
            {
                return View(recordset.Skip(number * total).Take(number));
            }

            return View(recordset.Skip(number * page).Take(number));
        }

        // GET SKBusStops Detail page with id parameter
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);

            if (busStop == null)
            {
                return NotFound();
            }

            return View(busStop);
        }

        // GET SKBusStops Create page
        public IActionResult Create()
        {
            return View();
        }

        // POST SKBusStops Create to insert new data into database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BusStopNumber,GoingDowntown,Location,LocationHash")] BusStop busStop)
        {
            if (ModelState.IsValid)
            {
                busStop.LocationHash = HashLocation(busStop.Location);
                _context.Add(busStop);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(busStop);
        }

        /// <summary>
        /// string value is converted into integer by adding there ascii code number
        /// </summary>
        /// <param name="l">string to convert into integer number</param>
        /// <returns>integer number is returned </returns>
        private int HashLocation(string l)
        {
            int sum = 0;
            foreach(char c in l)
            {
                sum += (int)c;
            }
            return sum;
        }
       
        // GET SKBusStops Edit page
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);
            if (busStop == null)
            {
                return NotFound();
            }
            return View(busStop);
        }

        // POST SKBusStops Edit to update edited data 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BusStopNumber,GoingDowntown,Location,LocationHash")] BusStop busStop)
        {
            if (id != busStop.BusStopNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    busStop.LocationHash = HashLocation(busStop.Location);
                    _context.Update(busStop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BusStopExists(busStop.BusStopNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(busStop);
        }

        // GET SKBusStops Delete page with one parameter
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);
            if (busStop == null)
            {
                return NotFound();
            }

            return View(busStop);
        }

        // POST to delete data from database 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var busStop = await _context.BusStop.SingleOrDefaultAsync(m => m.BusStopNumber == id);
            _context.BusStop.Remove(busStop);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // check if busstop number is exist
        private bool BusStopExists(int id)
        {
            return _context.BusStop.Any(e => e.BusStopNumber == id);
        }


        /// <summary>
        /// Route selector page to be displayed
        /// </summary>
        /// <param name="busStopNumber">number of bus stop</param>
        /// <returns></returns>
        public async Task<IActionResult> RouteSelector(int? busStopNumber)
        {
            if (busStopNumber == null)
            {
                TempData["message"] = "Please Select Bus Stop Number";
                return RedirectToAction("Index");
            }

            try
            {
                var recordset = await _context.RouteStop.Where(a => a.BusStopNumber == busStopNumber).Include(a => a.BusRouteCodeNavigation).ToListAsync();
                if (recordset.Count > 0)
                {
                    if (recordset.Count == 1)
                    {
                        var routeStopId = _context.RouteStop.SingleOrDefault(a => a.BusStopNumber == busStopNumber).RouteStopId;    
                        return RedirectToAction(actionName: "RouteStopSchedule", controllerName: "SKRouteSchedule", routeValues: new { routeStopId = routeStopId });
                    }

                    TempData["number"] = busStopNumber;
                    TempData["location"] = _context.BusStop.SingleOrDefault(a => a.BusStopNumber == busStopNumber).Location;
                    return View(recordset);
                }    
            }
            catch (Exception)
            {
                TempData["message"] = "Error occured, please try another route stop";
                return RedirectToAction("Index");
            }

            TempData["message"] = "Sorry there is no result of the bus stop " + busStopNumber.ToString();
            return RedirectToAction("Index");
            
        }
    }
}

Bus Station/SKBusService/src/SKBusService/Controllers/SKDriverController.cs
/*
 *  SKDriverController.cs
 *  Assignment 5
 *  Created By:
 *      Soochang Kim, 7227663
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SKBusService.Models;
using Microsoft.AspNetCore.Http;

namespace SKBusService.Controllers
{
    public class SKDriverController : Controller
    {
        private readonly BusServiceContext _context;

        /// <summary>
        /// Class constructor
        /// </summary>
        /// <param name="context"></param>
        public SKDriverController(BusServiceContext context)
        {
            _context = context;    
        }

        /// <summary>
        /// To display index page
        /// </summary>
        /// <returns>View of index page</returns>
        public async Task<IActionResult> Index()
        {
            var busServiceContext = _context.Driver.Include(d => d.ProvinceCodeNavigation).OrderBy(a => a.FullName);
            return View(await busServiceContext.ToListAsync());
        }

        /// <summary>
        /// To display details page
        /// </summary>
        /// <param name="id">Driver id</param>
        /// <returns>View of details page</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "No driver id given";
                return RedirectToAction("Index");
            }

            var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                TempData["message"] = "No record for given driver id";
                return RedirectToAction("Index");
            }
            HttpContext.Session.SetString("Driver", driver.FirstName + " " + driver.LastName);
            return View(driver);
        }

        /// <summary>
        /// To display create page
        /// </summary>
        /// <returns>Vieow of create page</returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// To Save new driver record
        /// </summary>
        /// <param name="driver">Driver object</param>
        /// <returns>To index action only when addtion is success</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DriverId,City,DateHired,FirstName,FullName,HomePhone,LastName,PostalCode,ProvinceCode,Street,WorkPhone")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(driver);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "New Driver Record is inserted: " + driver.FirstName + " " + driver.LastName;
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", $"Exception thrown on Create: {ex.GetBaseException().Message}");
                }
            }
            return View(driver);
        }

        /// <summary>
        /// To display edit page
        /// </summary>
        /// <param name="id">Driver id</param>
        /// <returns>View of edit page</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "No driver id given";
                return RedirectToAction("Index");
            }

            var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                TempData["message"] = "No record for given driver id";
                return RedirectToAction("Index");
            }

            HttpContext.Session.SetString("Driver",driver.FirstName + " " + driver.LastName);
            ViewData["Driver"] = driver.FirstName + " " + driver.LastName;
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(a => a.Name) , "ProvinceCode", "Name", driver.ProvinceCode);
            return View(driver);
        }

        /// <summary>
        /// To Update driver record
        /// </summary>
        /// <param name="id">Driver id</param>
        /// <param name="driver">Driver object</param>
        /// <returns>To index action only when update is success</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DriverId,City,DateHired,FirstName,FullName,HomePhone,LastName,PostalCode,ProvinceCode,Street,WorkPhone")] Driver driver)
        {
            if (id != driver.DriverId)
            {
                ModelState.AddModelError("", "Invalid driver ID");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(driver);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Driver record is updated: " + driver.FirstName + " " + driver.LastName;
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DriverExists(driver.DriverId))
                    {
                        ModelState.AddModelError("", $"Driver ID '{driver.DriverId}' is not registered");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Someone else modified the original record .. re-retrieve it and re-apply your updates");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.GetBaseException().Message);
                }
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "Name", driver.ProvinceCode);
            return View(driver);
        }

        /// <summary>
        /// To display delete page
        /// </summary>
        /// <param name="id">Driver Id</param>
        /// <returns>View of delete page</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "No driver id given";
                return RedirectToAction("Index");
            }

            var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                TempData["message"] = "No record for given driver id";
                return RedirectToAction("Index");
            }
            HttpContext.Session.SetString("Driver", driver.FirstName + " " + driver.LastName);
            return View(driver);
        }

        /// <summary>
        /// To Delete driver record
        /// </summary>
        /// <param name="id">Driver Id</param>
        /// <returns>To index action when deletion is success</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var driver = await _context.Driver.SingleOrDefaultAsync(m => m.DriverId == id);
            try
            {
                _context.Driver.Remove(driver);
                await _context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                ViewData["message"]= "Deletion was failed: " + ex.GetBaseException().Message;
                return View(id);
            }
            TempData["message"] =  "Driver Record is deleted: " + driver.FirstName + " " + driver.LastName;
            return RedirectToAction("Index");
        }

        /// <summary>
        /// To check if the given id is exists
        /// </summary>
        /// <param name="id">Driver id</param>
        /// <returns>True if driver id is exist</returns>
        private bool DriverExists(int id)
        {
            return _context.Driver.Any(e => e.DriverId == id);
        }
    }
}

Bus Station/SKBusService/src/SKBusService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - A2BusService</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/logo.png" class="logo" />SKBusService</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="SKBusRoute" asp-action="Index">Bus Routes</a></li>
                    <li><a asp-area="" asp-controller="SKBusStop" asp-action="Index">Bus Stops</a></li>
                    <li><a asp-area="" asp-controller="SKDriver" asp-action="Index">Drivers</a></li>
                    @if (User.IsInRole("administrators"))
                    {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Security<span class="caret"></span></a>
                        <ul class="dropdown-menu ">
                            <li class="dropdwon-header">User/Role Administration</li>
                            <li><a asp-area="" asp-controller="SKUserMaintenance" asp-action="Index">User Maintenance</a></li>
                            <li><a asp-area="" asp-controller="SKRoleMaintenance" asp-action="Index">Role Maintenance</a></li>
                        </ul>
                    </li>
                    }
                </ul>
               
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <!--Temp data message will be displayed before guest pages-->
        <h2 class="text-danger" style="font-weight:bold">@(TempData["message"] == null ? ViewData["message"] : TempData["message"])</h2>
        @RenderBody()
        <hr />
        <footer>
            <ul class="nav navbar-nav" style="clear:both">
                <li><a href="mailto:Skim7663@conestogac.on.ca">Soochang Kim</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="">Section 1</a></li>
            </ul>
            <ul class="nav navbar-nav" style="float:right">
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>