Bus Station/SKBusService/src/SKBusService/Models/AccountViewModels/ResetPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SKBusService.Models.AccountViewModels
{
    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }
}

Bus Station/SKBusService/src/SKBusService/Controllers/SKUserMaintenanceController.cs
/*
 *  SKUserMaintenanceController.cs
 *  Assignment 5
 *  Created By:
 *      Soochang Kim, 7227663
 */
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using SKBusService.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using SKBusService.Models.AccountViewModels;
using System.Security.Claims;
using SKBusService.Models.Db;
using Microsoft.EntityFrameworkCore;
using System.Collections;
using System.Collections.Generic;

namespace SKBusService.Controllers
{
    [Authorize(Roles = "administrators")] 
    public class SKUserMaintenanceController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly AspNetContext _context;
        public SKUserMaintenanceController(
            UserManager<ApplicationUser> userManger,
            AspNetContext context,
            SignInManager<ApplicationUser> signInManager,
            RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManger;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _context = context;
        }

        
        /// <summary>
        /// Display Index page
        /// </summary>
        /// <returns> Index view </returns>
        public IActionResult Index()
        {
            var allUsers = _context.AspNetUsers.Include(a => a.AspNetUserRoles);
            var sortedUsers = (allUsers.ToList()).OrderByDescending(a => a.LockoutEnd != null).ThenBy(a => a.UserName);
            return View(sortedUsers);
        }

        /// <summary>
        /// To delete user information
        /// </summary>
        /// <param name="id"> user id</param>
        /// <returns> Index page </returns>
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = _userManager.Users.Where(a => a.Id == id).SingleOrDefault();
            
            try
            {
                IdentityResult result;
                var userRoles = _context.AspNetUserRoles.Where(a => a.UserId == id);

                if(userRoles == null || userRoles.Count() == 0)
                    result = await _userManager.DeleteAsync(user);
                // if user role is in administrators
                else if (userRoles.SingleOrDefault(a => a.RoleId =="1") != null ) 
                {
                    throw new Exception("User is in administrators role");
                }
                else
                {
                    _context.AspNetUserRoles.RemoveRange(userRoles);
                    await _context.SaveChangesAsync();
                    result = await _userManager.DeleteAsync(user);
                }
                TempData["message"] = $"User '{user.UserName}' has been deleted.";
            }
            catch (Exception ex)
            {
                TempData["message"] = $"Fail to delete '{user.UserName}': {ex.GetBaseException().Message}.";
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Display reset page
        /// </summary>
        /// <param name="id"> User id</param>
        /// <returns> Register view model</returns>
        public async Task<IActionResult> ResetPassword(string id)
        {
            if (!User.IsInRole("administrators"))
            {
                TempData["message"] = "Sorry, your role doesn't has authority for it";
                return RedirectToAction("Index");
            }
            if (id == null)
            {
                TempData["message"] = "Sorry, the user Id was null";
                return RedirectToAction("Index");
            }

            ApplicationUser user = await _userManager.FindByIdAsync(id);

            var userRoles = _context.AspNetUserRoles.Where(a => a.UserId == id);
            if(userRoles.SingleOrDefault(a => a.RoleId == "1") != null)
            {
                TempData["message"] = "Sorry, the user Id was not found";
                return RedirectToAction("Index");
            }

            if (id == null)
            {
                TempData["message"] = "Sorry, the user Id was not found";
                return RedirectToAction("Index");
            }

            RegisterViewModel rvm = new RegisterViewModel();
            rvm.UserName = user.UserName;
            return View(rvm);
        }

        /// <summary>
        /// Display user reset password
        /// </summary>
        /// <param name="id"> User id</param>
        /// <param name="register"> Model to reset user password </param>
        /// <returns> Reset page</returns>
        [HttpPost]
        public async Task<IActionResult> ResetPassword(string id, RegisterViewModel register)
        {
            if(register == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _userManager.FindByIdAsync(id);
            
            if (user.Id == null)
            {
                return NotFound();
            }

            try
            {
                IdentityResult result;

                await _userManager.RemovePasswordAsync(user);
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);

                result = await _userManager.ResetPasswordAsync(user, code, register.Password);
                if (result.Succeeded)
                {
                    TempData["message"] = $"{user.UserName}'s password was successfully changed";
                    return RedirectToAction("Index");
                }
                else
                {
                    throw new Exception(result.Errors.FirstOrDefault().Description);
                }
            }
            catch(Exception ex)
            {
                TempData["message"] = $"Failed to change password: {ex.GetBaseException().Message}";
            }

            RegisterViewModel rvm = new RegisterViewModel();
            rvm.UserName = user.UserName;
            return View(rvm);
        }

        /// <summary>
        /// Lock user account
        /// </summary>
        /// <param name="user"> user </param>
        /// <returns> success if lock process success</returns>
        private async Task<IdentityResult> lockAccountAsync(ApplicationUser user)
        {
            user.AccessFailedCount = 5;
            user.LockoutEnd = new DateTimeOffset(DateTime.MaxValue, TimeSpan.Zero);
            return await _userManager.UpdateAsync(user);
        }

        /// <summary>
        /// Unlock user account
        /// </summary>
        /// <param name="user"> User </param>
        /// <returns> Result </returns>
        private async Task<IdentityResult> unLockAccountAsync(ApplicationUser user)
        {
            IdentityResult result = await _userManager.ResetAccessFailedCountAsync(user);
            if (result.Succeeded)
                return await _userManager.SetLockoutEndDateAsync(user, null);
            return result;
        }


        /// <summary>
        /// To change user's lock status
        /// </summary>
        /// <param name="id"> user </param>
        /// <returns> index view </returns>
        public async Task<IActionResult> ChangeLockState(string id)
        {           
            try
            {
                ApplicationUser user;
                IdentityResult result;
                user = await _userManager.FindByIdAsync(id);

                result = await ((user.LockoutEnd > DateTime.Now) ? unLockAccountAsync(user) : lockAccountAsync(user));

                if (result.Succeeded)
                {
                    TempData["message"] = $"{((user.LockoutEnd > DateTime.Now) ? "Locked" : "Unlocked")} account for : {user.UserName}";
                }
                else
                {
                    throw new Exception(result.Errors.FirstOrDefault().Description);
                }

            }
            catch(Exception ex)
            {
                TempData["message"] = $"Fail to change state: {ex.GetBaseException().Message}";
            }

            return RedirectToAction("Index");
        }
    }
}

Bus Station/SKBusService/src/SKBusService/Views/SKUserMaintenance/Index.cshtml
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore
@using SKBusService.Models.DB

@model IEnumerable<AspNetUsers>

@{
    ViewData["title"] = "User Maintenance";
}

<h2>@ViewData["title"]</h2>

<table class="table">
    <thead>
        <tr>
            <th>User Name</th>
            <th>User Email</th>
            <th>Locked Out</th>
            <th>Authenticated</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.UserName</td>
                <td>@item.Email</td>
                <td>@(item.LockoutEnd == null ? "No" : "Yes") </td>

                <td>@(item.PasswordHash == null || @item.PasswordHash == "" ? "Yes" : "No") </td>
                <td>
                    <a asp-action="ChangeLockState" asp-route-id="@item.Id">@(item.LockoutEnd > DateTime.Now ? "Unlock" : "Lock") User</a>
                @if (User.IsInRole("administrators"))
                {
                    @:| 
                    <a asp-action="ResetPassword" asp-route-id="@item.Id">Reset Password</a>
                }   

                @{
                    var authorized = false;
                    foreach (var role in item.AspNetUserRoles)
                    {
                        if (role.RoleId == "1")
                        {
                            authorized = true;
                        }
                    }
                    if (!authorized)
                    {
                        @:|
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                }
                 </td>
            </tr>
        }
    </tbody>
</table>

Bus Station/SKBusService/src/SKBusService/Views/SKUserMaintenance/ResetPassword.cshtml
@model RegisterViewModel
@{
    ViewData["Title"] = "Change Password";
}

<h2>@ViewData["Title"].</h2>

<form asp-controller="SKUserMaintenance" asp-action="ResetPassword" method="post" class="form-horizontal" >
    <h4>Change New password</h4>

    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="UserName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input disabled="disabled" asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Change Password</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");
        
        }
}